import test from 'node:test';
import assert from 'node:assert/strict';
import {POSES,DIFFICULTIES} from '../dist/game-core.mjs';
import {RoomGame,validFrame,cleanName} from '../dist/room-core.mjs';
import {galleryLayout,containRect} from '../dist/gallery.mjs';

function frame(game,time,index=game.poseIndex){return{raw:POSES[index].points.map(p=>p?{x:1-(p.x*100+320)/640,y:(p.y*100+260)/480,visibility:1}:null),width:640,height:480,visible:true,time,token:game.token};}
function receiveAll(g,time,poses={}){for(const id of g.contenders)g.receive(id,frame(g,time,poses[id]??g.poseIndex),time);}
function prepare(g,time=1000){receiveAll(g,time);g.tick(time);assert.equal(g.phase,'prepare');for(let t=time+100;t<=time+3000;t+=100){receiveAll(g,t);g.tick(t);}assert.equal(g.phase,'playing');return time+3000;}
function complete(g,start,poses={}){for(let t=start+100;t<start+5000;t+=100){receiveAll(g,t,poses);g.tick(t);}g.tick(start+5000);assert.equal(g.phase,'settling');g.tick(start+6000);return start+6000;}

test('1 through 30 participants; 31st rejected; host is not counted',()=>{for(let n=1;n<=30;n++){const g=new RoomGame();for(let i=0;i<n;i++)g.join(String(i),'P',0);assert.equal(g.arm(0),true);assert.equal(g.roster.length,n);}const g=new RoomGame();assert.equal(g.arm(0),false);for(let i=0;i<30;i++)g.join(String(i),'P',0);assert.throws(()=>g.join('31','extra',0),/30명/);});
test('all four difficulties contain ten unique poses and shuffle without duplicates',()=>{assert.equal(new Set(POSES.map(p=>p.id)).size,40);for(const difficulty of ['all',...Object.keys(DIFFICULTIES)]){const g=new RoomGame({random:()=>.4});g.reset({rounds:5,difficulty});g.join('1','P',0);g.arm(0);assert.equal(g.poseOrder.length,difficulty==='all'?40:10);assert.equal(new Set(g.poseOrder).size,g.poseOrder.length);assert.ok(g.poseOrder.every(i=>difficulty==='all'||POSES[i].difficulty===difficulty));}});
test('all players must remain fully visible for the complete three-second countdown',()=>{const g=new RoomGame();g.join('a','A',0);g.join('b','B',0);g.arm(0);g.receive('a',frame(g,100),100);g.tick(100);assert.equal(g.phase,'waiting');receiveAll(g,200);g.tick(200);assert.equal(g.end,3200);g.receive('b',null,300);g.tick(300);assert.equal(g.phase,'waiting');receiveAll(g,400);g.tick(400);assert.equal(g.end,3400);});
test('single-player completes one round with a real matching score and one winner',()=>{const g=new RoomGame();g.reset({rounds:1});g.join('p','Practice',0);g.arm(0);const start=prepare(g);complete(g,start);assert.equal(g.phase,'finished');assert.equal(g.winner,'p');assert.equal(g.rounds[0].scores.p,100);});
test('thirty players complete five rounds; top average wins',()=>{const g=new RoomGame({random:()=>.7});g.reset({rounds:5});for(let i=0;i<30;i++)g.join(String(i),`P${i}`,0);g.arm(0);let now=1000;for(let round=0;round<5;round++){const start=prepare(g,now),poses=Object.fromEntries(g.contenders.slice(1).map(id=>[id,(g.poseIndex+1)%POSES.length]));now=complete(g,start,poses);if(round<4){assert.equal(g.phase,'result');assert.equal(g.snapshot(now).round,round+1);now+=5000;g.tick(now);assert.equal(g.phase,'waiting');}}assert.equal(g.phase,'finished');assert.equal(g.winner,'0');assert.equal(g.ranking()[0].average,100);assert.equal(g.rounds.length,5);});
test('tie break involves only tied leaders and selects a single winner',()=>{const g=new RoomGame({random:()=>.4});g.reset({rounds:1});for(const id of ['a','b','c'])g.join(id,id,0);g.arm(0);let now=complete(g,prepare(g),{c:(g.poseIndex+1)%40});assert.equal(g.phase,'result');assert.equal(g.suddenDeath,true);assert.deepEqual(g.contenders,['a','b']);now+=5000;g.tick(now);const start=prepare(g,now);complete(g,start,{b:(g.poseIndex+1)%40});assert.equal(g.phase,'finished');assert.equal(g.winner,'a');assert.equal(g.extra.length,1);});
test('missing scoring data retries instead of inventing a score',()=>{const g=new RoomGame();g.reset({rounds:1});g.join('p','P',0);g.arm(0);const start=prepare(g);g.receive('p',null,start+50);g.tick(start+5000);g.tick(start+6000);assert.equal(g.phase,'waiting');assert.equal(g.rounds.length,0);assert.equal(g.winner,null);});
test('disconnect/rejoin preserves identity and retries the current round',()=>{const g=new RoomGame();g.join('a','A',0);g.arm(0);const start=prepare(g);g.leave('a');g.tick(start+100);assert.equal(g.phase,'waiting');assert.equal(g.members.size,1);g.join('a','New name ignored',start+200);assert.equal(g.members.get('a').name,'A');receiveAll(g,start+300);g.tick(start+300);assert.equal(g.phase,'prepare');assert.throws(()=>g.join('new','N',start),/경기 중/);});
test('malformed, stale, hidden, duplicate and wrong-round data never earns scores',()=>{const g=new RoomGame();g.join('a','A',0);g.arm(0);const start=prepare(g);const good=frame(g,start+100);assert.equal(validFrame(good),true);const bad=structuredClone(good);bad.raw[11].x=NaN;assert.equal(validFrame(bad),false);assert.equal(g.receive('a',bad,start+100),false);g.receive('a',{...good,visible:false},start+100);assert.equal(g.ready('a',start+100),false);assert.equal(g.receive('a',good,start+101),false);assert.equal(g.receive('a',frame(g,start+5000),start+200),false);for(let t=start+200;t<start+1000;t+=100)g.receive('a',{...frame(g,t),token:g.token-1},t);assert.equal(g.windows.get('a').best,null);assert.equal(g.receive('a',frame(g,start+1100),start+2400),false);});
test('one-second grace accepts delayed pre-deadline samples, not post-deadline poses',()=>{const g=new RoomGame();g.join('a','A',0);g.arm(0);const start=prepare(g);g.tick(start+5000);for(let t=start+4450;t<=start+4950;t+=100)g.receive('a',frame(g,t),start+5100+(t-start-4450));assert.equal(g.windows.get('a').best,100);g.receive('a',frame(g,start+5050),start+5800);assert.ok(g.windows.get('a').samples.every(p=>p.time<g.end));});
test('new match resets scores and cannot use leftover round windows',()=>{const g=new RoomGame();g.reset({rounds:1});g.join('a','A',0);g.arm(0);complete(g,prepare(g));g.reset();assert.equal(g.members.get('a').score,null);assert.equal(g.windows.size,0);assert.equal(g.winner,null);assert.equal(g.phase,'lobby');assert.equal(g.members.size,1);});
test('input names and gallery layouts stay within limits',()=>{assert.equal(cleanName('  A\nB  '),'AB');assert.equal(cleanName('x'.repeat(100)).length,16);for(let n=1;n<=30;n++){const cells=galleryLayout(n);assert.equal(cells.length,n<=8?n+1:n);for(const b of cells)assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=1280.01&&b.y+b.h<=720.01);}const b=containRect(640,480,{x:0,y:0,w:420,h:236});assert.equal(b.h,236);assert.ok(b.w<420);assert.ok(b.x>0);});
