import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {HostSession,PROTOCOL,validCode,randomCode} from '../dist/room-session.mjs';
class Channel extends EventEmitter{constructor(peer){super();this.peer=peer;this.open=true;this.sent=[];}send(m){this.sent.push(structuredClone(m));}close(){if(this.open){this.open=false;this.emit('close');}}}
const token=i=>String(i).padStart(36,'a');
function hello(s,i,secret=token(i)){const c=new Channel(`peer${i}`);s.attach(c);c.emit('data',{type:'hello',name:`P${i}`,version:PROTOCOL,token:secret});return c;}
test('eight independent channels join; ninth cannot; unauthorized media rejected',()=>{let now=0,nextId=0;const s=new HostSession({now:()=>now,id:()=>String(nextId++)});const clients=Array.from({length:8},(_,i)=>hello(s,i));assert.equal(s.game.members.size,8);const ninth=hello(s,9);assert.equal(ninth.sent.at(-1).type,'reject');assert.equal(s.acceptCall({peer:'peer0',metadata:{memberId:'0',token:token(0)}}),'0');assert.equal(s.acceptCall({peer:'imposter',metadata:{memberId:'0',token:token(0)}}),null);assert.equal(s.acceptCall({peer:'peer0',metadata:{memberId:'0',token:'wrong'}}),null);s.broadcast();for(const c of clients){const snapshot=c.sent.at(-1);assert.equal(snapshot.state.members.length,8);assert.equal(JSON.stringify(snapshot).includes(token(0)),false);}s.close();});
test('private reconnect token retains participant identity during a match',()=>{let now=0,nextId=0;const s=new HostSession({now:()=>now,id:()=>String(nextId++)});const c=hello(s,1);const memberId=c.sent[0].memberId;s.game.arm(0);c.close();now=1000;const resumed=hello(s,2,token(1));assert.equal(resumed.sent[0].memberId,memberId);const duplicate=hello(s,3,token(1));assert.equal(duplicate.sent[0].type,'reject');assert.equal(s.game.members.size,1);s.close();});
test('invisible camera or media loss clears readiness; stale clients are disconnected',()=>{let now=1000;const s=new HostSession({now:()=>now,id:()=> 'a',mediaReady:()=>false});const c=hello(s,0);s.game.members.get('a').ready=true;c.emit('data',{type:'frame',frame:{}});assert.equal(s.game.ready('a',now),false);s.game.arm(now);now=14001;s.tick();assert.equal(c.open,false);assert.equal(s.game.members.get('a').connected,false);s.close();});
test('host can remove in lobby; unauthenticated channels expire',()=>{let now=1000;const s=new HostSession({now:()=>now,id:()=> 'a'});const c=hello(s,0);s.remove('a');assert.equal(s.game.members.size,0);assert.equal(c.sent.at(-1).type,'reject');const idle=new Channel('idle');s.attach(idle);now=10000;s.tick();assert.equal(idle.open,false);s.close();});
test('protocol mismatches fail and room codes are generated in the expected alphabet',()=>{const s=new HostSession();const c=new Channel('old');s.attach(c);c.emit('data',{type:'hello',version:0,token:token(0)});assert.equal(c.sent[0].type,'reject');for(let i=0;i<100;i++)assert.equal(validCode(randomCode()),true);assert.equal(validCode('abc'),false);s.close();});
